"""WhatsApp + GitHub formatting for PR reviews (Plan 63-A)."""

from __future__ import annotations

from app.reviews.models import (
    PullRequestInfo,
    ReviewFinding,
    ReviewSummary,
    RiskLevel,
    Severity,
)


def _severity_emoji(severity: Severity) -> str:
    return {
        Severity.critical: "\U0001f534",  # 🔴
        Severity.warning: "\u26a0\ufe0f",  # ⚠️
        Severity.suggestion: "\U0001f4a1",  # 💡
        Severity.nitpick: "\U0001f4dd",  # 📝
    }.get(severity, "")


def _risk_emoji(risk: RiskLevel) -> str:
    return {
        RiskLevel.low: "\U0001f7e2",  # 🟢
        RiskLevel.medium: "\U0001f7e1",  # 🟡
        RiskLevel.high: "\U0001f7e0",  # 🟠
        RiskLevel.critical: "\U0001f534",  # 🔴
    }.get(risk, "")


def format_review_summary(summary: ReviewSummary, pr: PullRequestInfo) -> str:
    """Format a ReviewSummary for WhatsApp delivery."""
    risk = f"{_risk_emoji(summary.risk_level)} {summary.risk_level.value.capitalize()}"
    stats = summary.stats

    lines = [
        f"\U0001f50d *PR Review: #{pr.number} \u2014 {summary.title}*",
        "",
        f"*Riesgo:* {risk}",
        f"*Archivos:* {summary.files_reviewed} revisados | +{stats.get('additions', 0)} -{stats.get('deletions', 0)} | {stats.get('findings_total', 0)} hallazgos",
        "",
        summary.overview,
    ]

    if summary.key_changes:
        lines.append("")
        lines.append("*Cambios clave:*")
        for change in summary.key_changes[:5]:
            lines.append(f"\u2022 {change}")

    # Top findings (max 5, highest severity first)
    if summary.findings:
        lines.append("")
        lines.append("*Hallazgos principales:*")
        for f in summary.findings[:5]:
            emoji = _severity_emoji(f.severity)
            lines.append(f"{emoji} *{f.category.value}* `{f.path}:{f.line}` \u2014 {f.body[:120]}")

    if summary.files_skipped > 0:
        lines.append("")
        lines.append(f"_{summary.files_skipped} archivos omitidos (generados/overflow)_")

    duration_s = summary.duration_ms / 1000
    lines.append("")
    lines.append(f"\U0001f517 {pr.url} | {duration_s:.1f}s")

    return "\n".join(lines)


def format_finding_for_github(finding: ReviewFinding) -> str:
    """Format a single ReviewFinding as a GitHub PR review comment body."""
    emoji = _severity_emoji(finding.severity)
    parts = [
        f"{emoji} **[{finding.category.value}]** {finding.body}",
    ]
    if finding.suggestion:
        parts.append("")
        parts.append("```suggestion")
        parts.append(finding.suggestion)
        parts.append("```")
    parts.append("")
    parts.append(f"_Confidence: {finding.confidence:.0%} | Generated by LocalForge_")
    return "\n".join(parts)
