from typing import Protocol, runtime_checkable


@runtime_checkable
class PlatformClient(Protocol):
    async def send_message(self, to_id: str, text: str) -> str | None: ...

    async def download_media(self, media_id: str) -> bytes: ...

    async def mark_as_read(self, message_id: str) -> None: ...

    async def send_typing_indicator(self, to_id: str) -> None: ...

    async def remove_typing_indicator(
        self, to_id: str, indicator_id: str | None = None
    ) -> None: ...

    def format_text(self, text: str) -> str: ...

    def platform_name(self) -> str: ...
