"""AI PR Description Generator — Generates title + body for a PR using Gemini."""

import asyncio
import os
import time

import httpx
from google import genai

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GITHUB_REPOSITORY = os.getenv("GITHUB_REPOSITORY")
PR_NUMBER = os.getenv("PR_NUMBER")

if not GITHUB_TOKEN or not GEMINI_API_KEY:
    print("Skipping AI Description: Missing GITHUB_TOKEN or GEMINI_API_KEY")
    exit(0)

GITHUB_HEADERS = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


async def get_pr_diff() -> str | None:
    """Fetch the PR diff from GitHub API."""
    if not PR_NUMBER:
        print("No PR number found.")
        return None

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3.diff",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/pulls/{PR_NUMBER}"

    async with httpx.AsyncClient() as client:
        response = await client.get(url, headers=headers)
        if response.status_code == 200:
            return response.text
        print(f"Failed to fetch diff: {response.status_code} {response.text}")
        return None


async def generate_description(diff_text: str) -> tuple[str, str] | None:
    """Generate PR title and body using Gemini. Returns (title, body) or None."""
    client = genai.Client(api_key=GEMINI_API_KEY)

    prompt = f"""
    You are a Senior Software Engineer. Based on the following git diff,
    generate a Pull Request title and description.

    Rules:
    - Title: concise, imperative mood, max 70 chars (e.g. "Add user authentication endpoint")
    - Description: structured Markdown with sections: ## Summary, ## Changes, ## Notes (if any)
    - Be concise and focus on the "why" and "what"

    Respond EXACTLY in this format (no extra text):
    TITLE: <your title here>
    BODY:
    <your markdown description here>

    GIT DIFF:
    ```diff
    {diff_text[:20000]}
    ```
    """

    max_retries = 3
    base_delay = 2

    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model="gemini-2.0-flash",
                contents=prompt,
            )
            text = str(response.text)
            return _parse_response(text)
        except Exception as e:
            error_str = str(e).lower()
            is_rate_limit = any(
                keyword in error_str
                for keyword in ("ratelimit", "quota", "429", "resource_exhausted")
            )
            if is_rate_limit and attempt < max_retries - 1:
                delay = base_delay * (2**attempt)
                print(f"Rate limited. Retrying in {delay}s...")
                time.sleep(delay)
                continue
            print(f"Gemini Error: {e}")
            return None

    return None


def _parse_response(text: str) -> tuple[str, str] | None:
    """Parse the TITLE:/BODY: response format."""
    if "TITLE:" not in text or "BODY:" not in text:
        print("Could not parse AI response.")
        return None

    title_part = text.split("BODY:")[0]
    title = title_part.replace("TITLE:", "").strip()

    body = text.split("BODY:", 1)[1].strip()

    if not title or not body:
        print("Empty title or body from AI.")
        return None

    return title, body


async def update_pr(title: str, body: str) -> None:
    """Update the PR title and body via GitHub API."""
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/pulls/{PR_NUMBER}"

    async with httpx.AsyncClient() as client:
        resp = await client.patch(
            url,
            headers=GITHUB_HEADERS,
            json={"title": title, "body": body},
        )
        if resp.status_code == 200:
            print("PR description updated successfully!")
        else:
            print(f"Failed to update PR: {resp.status_code} {resp.text}")


async def main() -> None:
    print(f"Generating AI description for {GITHUB_REPOSITORY} PR #{PR_NUMBER}")

    diff = await get_pr_diff()
    if not diff:
        print("No diff found or empty diff.")
        return

    print(f"Diff size: {len(diff)} chars")

    result = await generate_description(diff)
    if result:
        title, body = result
        body += "\n\n---\n*Generated by WasAP AI*"
        print(f"Generated title: {title}")
        await update_pr(title, body)
    else:
        print("No description generated.")


if __name__ == "__main__":
    asyncio.run(main())
