"""AI Code Reviewer — Fetches PR diff, analyzes with Gemini, posts review comment."""

import asyncio
import os

import httpx
from google import genai

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GITHUB_REPOSITORY = os.getenv("GITHUB_REPOSITORY")
PR_NUMBER = os.getenv("PR_NUMBER")

if not GITHUB_TOKEN or not GEMINI_API_KEY:
    print("Skipping AI Review: Missing GITHUB_TOKEN or GEMINI_API_KEY")
    exit(0)


async def get_pr_diff() -> str | None:
    """Fetch the PR diff from GitHub API."""
    if not PR_NUMBER:
        print("No PR number found. Running locally?")
        return None

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3.diff",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/pulls/{PR_NUMBER}"

    async with httpx.AsyncClient() as client:
        response = await client.get(url, headers=headers)
        if response.status_code == 200:
            return response.text
        print(f"Failed to fetch diff: {response.status_code} {response.text}")
        return None


async def analyze_code(diff_text: str) -> str | None:
    """Send diff to Gemini for analysis."""
    client = genai.Client(api_key=GEMINI_API_KEY)

    prompt = f"""
    You are a Senior Software Engineer acting as a Code Reviewer.
    Review the following code changes (git diff) for a Pull Request.

    Focus on:
    1. Bugs or Logic Errors (Critical)
    2. Security Vulnerabilities
    3. Performance Issues
    4. Code Quality & Best Practices (Pythonic style, clean code)

    Be concise, constructive, and friendly.
    If the code looks good, just say "LGTM!" and maybe a small compliment.
    Do NOT nitpick on trivial formatting if it looks like a linter would catch it.

    Format your response in Markdown.

    GIT DIFF:
    ```diff
    {diff_text[:30000]}
    ```
    """

    try:
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt,
        )
        return str(response.text)
    except Exception as e:
        print(f"Gemini Error: {e}")
        return None


async def post_comment(review_body: str) -> None:
    """Post the review as a comment on the PR."""
    if not review_body:
        return

    final_body = review_body + "\n\n*Generated by WasAP AI Reviewer*"

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/issues/{PR_NUMBER}/comments"

    async with httpx.AsyncClient() as client:
        resp = await client.post(url, headers=headers, json={"body": final_body})
        if resp.status_code == 201:
            print("Comment posted successfully!")
        else:
            print(f"Failed to post comment: {resp.status_code} {resp.text}")


async def main() -> None:
    print(f"Starting AI Review for {GITHUB_REPOSITORY} PR #{PR_NUMBER}")

    diff = await get_pr_diff()
    if not diff:
        print("No diff found or empty diff.")
        return

    print(f"Diff size: {len(diff)} chars")

    review = await analyze_code(diff)
    if review:
        print("Review generated. Posting to GitHub...")
        await post_comment(review)
    else:
        print("No review generated.")


if __name__ == "__main__":
    asyncio.run(main())
